name: Deploy

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '16.x'

jobs:
  deploy-storybook:
    name: Deploy Storybook

    # Prevent creating a deployment on forks
    if: github.repository == 'qiskit-community/qiskit-web-components'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - run: npm ci
      - run: npm run storybook:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
