name: Deploy

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '14.x'

jobs:
  deploy-storybook:
    name: Deploy Storybook

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn storybook:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
